# --- Identidad del sitio ---
title: "pruebaPAG"
description: "Pagina de pruebas"
# URL pública del usuario y base del proyecto (¡importante para rutas!)
url: "https://zotexd.github.io"
baseurl: "/pruebaPAG.github.io"

# --- Build / Markdown ---
markdown: kramdown
kramdown:
  input: GFM

# Páginas bonitas (/ruta/ en vez de .html)
permalink: pretty

# Tema que está usando Actions
theme: jekyll-theme-primer

# Plugins soportados por GitHub Pages (opcional)
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# --- Collections para las carpetas de series ---
collections:
#activos
  saneka:
    output: true
    permalink: /saneka/:name/
  ririsa:
    output: true
    permalink: /ririsa/:name/
  "100novias":            # clave entre comillas por empezar con número
    output: true
    permalink: /100novias/:name/
  megami:
    output: true
    permalink: /megami-no-cafe/:name/
  dream-jumbo-girl:
    output: true
    permalink: /dream-jumbo/:name/
#joints
  medalist:
    output: true
    permalink: /medalist/:name/
  marchen-crown:
    output: true
    permalink: /marchen-crown/:name/
#terminados
  komi:
    output: true
    permalink: /komi/:name/
  oshi-no-ko:
    output: true
    permalink: /oshi-no-ko/:name/

# --- Defaults: aplica layout caps automáticamente dentro de cada colección ---
defaults:
# activos (cambios en saneka y ririsa para que no fallen, test)
  - scope:
      type: saneka
    values:
      layout: caps
  - scope:
      type: ririsa
    values:
      layout: caps
  - scope:
      type: "100novias"
    values:
      layout: caps
  - scope:
      type: megami
    values:
      layout: caps
  - scope:
      type: dream
    values:
      layout: caps
# joints
  - scope:
      type: medalist
    values:
      layout: caps
  - scope:
      type: marchen-crown
    values:
      layout: caps
# terminados
  - scope:
      type: komi
    values:
      layout: caps
  - scope:
      type: oshi-no-ko
    values:
      layout: caps

# --- Archivos/carpetas a excluir del build (se amplía si hace falta) ---
exclude:
  - node_modules
  - vendor
  - README.md
  - checklist.txt
  - guia_rapida.txt

# --- Incluir explícitamente assets si lo necesita ---
include:
  - assets
