# --- Identidad del sitio ---
title: "EnchiladaWEB"
description: "Pagina de EnchiladaNoSekai"
url: "https://enchiladaScan.github.io"
baseurl: "/enchiladaweb"

# --- Build / Markdown ---
markdown: kramdown
kramdown:
  input: GFM

# Páginas bonitas (/ruta/ en vez de .html)
permalink: pretty

# Tema que está usando Actions
theme: jekyll-theme-primer

# Plugins soportados por GitHub Pages (opcional)
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# --- Collections para las carpetas de series ---
collections:
#activos
  witchriv:
    output: true
    permalink: /witchriv/:name/
  goldship:
    output: true
    permalink: /goldship/:name/
  #"100novias":            # clave entre comillas por empezar con número
    #output: true
    #permalink: /100novias/:name/
  megami:
    output: true
    permalink: /megami-no-cafe/:name/
  dream-jumbo-girl:
    output: true
    permalink: /dream-jumbo/:name/
  ore-no-ichizu-jama:
    output: true
    permalink: /ore-no-ichizu-jama/:name/
  shiori-experience:
    output: true
    permalink: /shiori-experience/:name/
  hatori-to-furuta:
    output: true
    permalink: /hatori-to-furuta/:name/
  idolatry:
    output: true
    permalink: /idolatry/:name/
  umine:
    output: true
    permalink: /umine/:name/

#joints
  medalist:
    output: true
    permalink: /medalist/:name/
  marchen-crown:
    output: true
    permalink: /marchen-crown/:name/
  heisei-haizanhei:
    output: true
    permalink: /heisei-haizanhei/:name/
#terminados
  ririsa:
    output: true
    permalink: /ririsa/:name/
  saneka:
    output: true
    permalink: /saneka/:name/
  komi:
    output: true
    permalink: /komi/:name/
  oshi-no-ko:
    output: true
    permalink: /oshi-no-ko/:name/
  nitamono-doushi:
    output: true
    permalink: /nitamono-doushi/:name/
  inori-no-nai:
    output: true
    permalink: /inori-no-nai/:name/
  

# --- Defaults: aplica layout caps automáticamente dentro de cada colección ---
defaults:
# activos
  - scope:
      type: ore-no-ichizu-jama
    values:
       layout: caps
  - scope:
      type: witchriv
    values:
      layout: caps
  - scope:
      type: goldship
    values:
      layout: caps
  - scope:
      type: "100novias"
    values:
      layout: caps
  - scope:
      type: megami
    values:
      layout: caps
  - scope:
      type: dream
    values:
      layout: caps
  - scope:
      type: umine
    values:
      layout: caps
# joints
  - scope:
      type: medalist
    values:
      layout: caps
  - scope:
      type: marchen-crown
    values:
      layout: caps
  - scope:
      type: heisei-haizanhei
    values:
      layout: caps
# terminados
  - scope:
      type: saneka
    values:
      layout: caps
  - scope:
      type: komi
    values:
      layout: caps
  - scope:
      type: oshi-no-ko
    values:
      layout: caps
  - scope:
      type: ririsa
    values:
      layout: caps

# --- Archivos/carpetas a excluir del build (se amplía si hace falta) ---
exclude:
  - node_modules
  - vendor
  - README.md
  - checklist.txt
  - guia_rapida.txt
  - faltantes.txt

# --- Incluir explícitamente assets si lo necesita ---
include:
  - assets
